Chore: Setup Docker
atlp-rwanda/atlp-apprenticeship-fn pull request #1
Opened 2023-08-18 11:56 UTC by rukundo-kevin

# PR Description

Set up docker  so that new images can be created for deployment.

## How has this been tested?

- Navigate to the repo
- run `docker build -t devpulse/atlp-apprenticeship-fn`.
 Or 
  `docker pull devpulse/atlp-apprenticeship-fn `
- run ` docker run  -p {port}:3000 devpulse/atlp-apprenticeship-fn`

2023-08-18 15:10 UTC, Virgile1k approved these changes
checked and approved

2023-08-22 07:20 UTC, NTElissa approved these changes

2023-08-22 13:17 UTC, ceelogre requested changes

2023-08-22 13:17 UTC, ceelogre commented on Dockerfile
> +FROM node:16-alpine
Let's use the latest node version.

2023-08-24 13:04 UTC, ceelogre approved these changes

2023-08-29 14:17 UTC, merged